export const GET_EXERCICES = 'GET_EXERCICES';
export const GET_EXERCICE = 'GET_EXERCICE';
export const EXERCICE_ERROR = 'EXERCICE_ERROR';
export const DELETE_EXERCICE = 'DELETE_EXERCICE';
export const ADD_EXERCICE = 'ADD_EXERCICE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_LESSONS='GET_LESSONS'


